on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [24]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'corretto'
          cache: 'maven'
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          avd-name: DeviceTest
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
          
     
          
      - name: install appium server
        run: npm i -g appium@next
        
      - name: install UiAutomator2
        run: appium driver install uiautomator2
        
      - name: check drivers
        run: appium driver list
             
      - name : run appium server
        run: appium --base-path=/wd/hub --use-plugins=relaxed-caps --session-override --use-plugins execute-driver &
        
      - name: Wait for Appium Server to start
        run: | 
         #until $(curl --output /dev/null --silent --head --fail http://localhost:4723/wd/hub/status); do 
         #echo "Waiting for Appium Server to start..."
         #sleep 1
         #done
         
      #- name: Wait 2 TEST
        #run: sleep 30

      - name: start emulator
        uses: reactivecircus/android-emulator-runner@v2  
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: mvn test -Dcucumber.filter.tags="@Version" -Dplatform=android -DdeviceType=emulator
